1st completed draft with the addition of Advanced exploiters strategy
jkasante74/Thesis_v2.0 pull request #1
Opened 2017-12-29 17:38 UTC by jkasante74

2018-02-05 15:08 UTC, ms280690 requested changes

2018-02-05 15:08 UTC, ms280690 commented on src/agents/Agent.java
> +	 * Agent Constructor : sets up parameters and other variables
I think the comments need to be updated

2018-02-05 15:08 UTC, ms280690 commented on src/agents/Agent.java
> +	 * Agent Constructor : sets up parameters and other variables
Not all parameters are valid now

2018-02-05 15:08 UTC, ms280690 commented on src/agents/Agent.java
> +	            throw new IllegalArgumentException("Unknown Strategy" );
Is there a formatting issue here?

2018-02-05 15:08 UTC, ms280690 commented on src/agents/Agent.java
>  	 *
agentStrategy is missing in list of parameters

2018-02-05 15:08 UTC, ms280690 commented on src/agents/Agent.java
> +	 * advancedDefector strategy cooperates or defects based on a strategic
No parameters here?

2018-02-05 15:08 UTC, ms280690 commented on src/agents/Agent.java
>  	char cooperateAll() {
Do you use these functions anywhere? same for defectAll

2018-02-05 15:08 UTC, ms280690 commented on src/agents/Agent.java
> +	 * advanceCooeprator strategy cooperates or defect based on acquired past
Need parameter information for advanceCooperator.

2018-02-05 15:08 UTC, ms280690 commented on src/agents/Agent.java
>  	/**
A lot of comments need to be updated throughout. Please check all function documentations.

2018-02-05 15:08 UTC, ms280690 commented on src/agents/Agent.java
> +
Is this tabbed too much?
Where do you use him in the setBeliefs function?

2018-02-05 15:08 UTC, ms280690 commented on src/agents/Agent.java
> +		if(opponentFirstAct != "D"){
Do you have a constant for "D"?

2018-02-05 15:08 UTC, ms280690 commented on src/agents/Agent.java
> +
Add error handling for divide by zero errors

2018-02-05 15:08 UTC, ms280690 commented on src/agents/Agent.java
> +	char dummy() {
Do you need this? Where do you use it?

2018-02-05 15:08 UTC, ms280690 commented on src/agents/Agent.java
> +	 * getOpponentPastInfo request for past opponent action from the HIM and
Update parameters

2018-02-05 15:08 UTC, ms280690 commented on src/agents/Agent.java
>  	char defectAll() {
Again do you use this anywhere?

2018-02-05 15:08 UTC, ms280690 commented on src/agents/Agent.java
> +			double opponentCooperatingRating = 	getOpponentCooperateRatio(requestingAgentID,opponentID,opponentCooperateRatio);
Formatting issue

2018-02-05 15:08 UTC, ms280690 commented on src/agents/Agent.java
> +			if ((opponentCooperatingRating >= 0.9)||(opponentFirstAct == "C")){
Formatting issue

2018-02-05 15:08 UTC, ms280690 commented on src/agents/Agent.java
> +				if (opponentInformation.equalsIgnoreCase("D"))
Do you have a constant for "D"?

2018-02-05 15:08 UTC, ms280690 commented on src/agents/Agent.java
> +				if((!opponentInformation.isEmpty())){
Could you do an "&&" here for infoAcquired and opponentInformation conditions

2018-02-05 15:08 UTC, ms280690 commented on src/agents/Agent.java
> +					//	JOptionPane.showMessageDialog(null, agentStrategy);
Remove the commented lines of code.

2018-02-05 15:08 UTC, ms280690 commented on src/agents/Agent.java
> +				opponentFirstAct = opponentInformation.substring(0, 1);
Do you use opponentFirstAct anywhere?

2018-02-05 15:08 UTC, ms280690 commented on src/agents/Agent.java
> +		case 0:
For some the cases, like case 1,
opponentInformation = him.requestOppPastInfo(requestingAgentID,
 					opponentID, infoRequestOption);
should be inside the if because if infoAcquired is false we do not use opponentInformation.

2018-02-05 15:08 UTC, ms280690 commented on src/agents/Agent.java
> +
You could do,
opponentCooperateRatio = 1.0;
if (opponentInformation.equalsIgnoreCase("D")){
opponentCooperateRatio = 0.0;
}

2018-02-05 15:08 UTC, ms280690 commented on src/agents/Agent.java
> +			if (infoAcquired) {
Calculate opponentInformation inside if.

2018-02-05 15:08 UTC, ms280690 commented on src/agents/Agent.java
> +			if (infoAcquired)
Calculate opponentInformation inside if

2018-02-05 15:08 UTC, ms280690 commented on src/agents/Agent.java
> +		double numOfCooperations = 0.0, numOfDefections = 0.0;
Declare and initialize all together.

2018-02-05 15:08 UTC, ms280690 commented on src/agents/Agent.java
> +			opponentCooperateRatio = numOfCooperations
handle divide by zero error

2018-02-05 15:08 UTC, ms280690 commented on src/agents/Agent.java
> +	protected double getOpponentCooperateRatio(int requestingAgentID, int opponentID, double opponentCooperateRatio) {
Do you need opponentCooperateRatio here?

2018-02-05 15:08 UTC, ms280690 commented on src/historicalInfo/HistoricalInfoMgr.java
> +	public static String agentsTournamentStatistics = "";
Declare agentsTournamentStatistics, experimentLeaderboard together.

2018-02-05 15:08 UTC, ms280690 commented on src/historicalInfo/HistoricalInfoMgr.java
>  	 * updates the SimLog data structure in HIR
Update doc

2018-02-05 15:08 UTC, ms280690 commented on src/historicalInfo/HistoricalInfoMgr.java
> +	public void updateAgActionsInReposiory(int currentTournamentIndex, int requestingAgentID, int opponentID,
Add doc

2018-02-05 15:08 UTC, ms280690 commented on src/historicalInfo/HistoricalInfoMgr.java
> +	public void updateMatchedAgentsScores(int requestingAgentID, int opponentID, float[] matchScores) {
Update doc

2018-02-05 15:08 UTC, ms280690 commented on src/historicalInfo/HistoricalInfoMgr.java
> +	public String requestOppPastInfo(int requestingAgentID, int opponentID, int requestOption) { // Not on class diagram
Update doc

2018-02-05 15:08 UTC, ms280690 commented on src/historicalInfo/HistoricalInfoMgr.java
> +	public String requestOppPastInfo(int requestingAgentID, int opponentID, int requestOption) { // Not on class diagram
Update doc

2018-02-05 15:08 UTC, ms280690 commented on src/historicalInfo/HistoricalInfoMgr.java
>  			if (oppActions.charAt(i) == 'D') {
Is there a constant for 'D'?

2018-02-05 15:08 UTC, ms280690 commented on src/historicalInfo/HistoricalInfoMgr.java
> +		for (int i = 0; i < agentPastInformation.length(); i++) {
Use constants

2018-02-05 15:08 UTC, ms280690 commented on src/settings/InputValidator.java
>  	public float infoRequestOption;
Group declarations

2018-02-05 15:08 UTC, ms280690 commented on src/simulationEngine/SimReport.java
> +		switch (requestOption) {
For a small number of options use if else if.

2018-02-05 15:08 UTC, ms280690 commented on src/simulationEngine/SimulationManager.java
> +	private void eliminateWithoutReplacement() {
Do we need these empty functions?

2018-02-07 09:52 UTC, jkasante74 commented
Respected Sir
Many thanks for all the comments. I deeply appreciate everything. Thanks alot
Ive made all the changes
cheers


    On Monday, February 5, 2018, 7:08:11 AM PST, Mehul Solanki <notifications@github.com> wrote:  
 
 
@ms280690 requested changes on this pull request.

In src/agents/Agent.java:
>  		
-		this.agents = agents;
-		this.him = him;
-		this.agentStrategies = agentStrategies;
+	}
+	
+	/**
+	 * Agent Constructor : sets up parameters and other variables

I think the comments need to be updated

In src/agents/Agent.java:
>  		
-		this.agents = agents;
-		this.him = him;
-		this.agentStrategies = agentStrategies;
+	}
+	
+	/**
+	 * Agent Constructor : sets up parameters and other variables

Not all parameters are valid now

In src/agents/Agent.java:
> +			break;
+			
+			case ADVANCE_COOPERATOR: agentAction = advanceCooperator(requestingAgentID, agentStrategy, opponentID, currentTournament, currentRound, infoRequestOption);
+			break;
+			
+			case ADVANCE_DEFECTOR: agentAction = advanceDefector(requestingAgentID, agentStrategy, opponentID, currentTournament, currentRound, infoRequestOption);
+			break;
+			
+			case ADVANCE_EXPLOITER: agentAction = advanceDefector(requestingAgentID, agentStrategy, opponentID, currentTournament, currentRound, infoRequestOption);
+			break;
+			
+			case DUMMY: agentAction = 'A';
+			break;
+					
+			default:
+	            throw new IllegalArgumentException("Unknown Strategy" );	

Is there a formatting issue here?

In src/agents/Agent.java:
>  	/**
-	 * getMatchedAgentActions method returns the chosen actions of paired agents
+	 * getAgentAction method returns the chosen action of the agent
 	 * 

agentStrategy is missing in list of parameters

In src/agents/Agent.java:
>  		return agentAction;
 
 	}
 	
 	
-	char advanceDefector(int requestingAgentID, int opponentID, int currentTournament, int currentRound) {
-		
-		return 0;
-	}
+	/**
+	 * advancedDefector strategy cooperates or defects based on a strategic

No parameters here?

In src/agents/Agent.java:
>  	}
 
 
+	/**
+	 * CooperateAll strategy cooperates at all times no matter what the opponent
+	 * does
+	 * 
+	 * @return COOPERATE : 'C'
+	 * 
+	 *         The algorithm and code structure for the CooperateAll Strategy
+	 *         could be located here
+	 *         http://www.prisoners-dilemma.com/java/ipdlx/ipdlx_javadocs/
+	 * 
+	 */
+	
 	char cooperateAll() {

Do you use these functions anywhere? same for defectAll

In src/agents/Agent.java:
>  
+	/**
+	 * advanceCooeprator strategy cooperates or defect based on acquired past

Need parameter information for advanceCooperator.

In src/agents/Agent.java:
>  
+		return matchAction;
+	}
+
+	
 	/**

A lot of comments need to be updated throughout. Please check all function documentations.

In src/agents/Agent.java:
>  
 		// Advanced agents assigns belief and game values about other agents
-		for (int i = 0; i < agentStrategies.length; i++) {
-			if ((agentStrategies[i] == ADVANCE_COOPERATOR)
-					|| (agentStrategies[i] == ADVANCE_DEFECTOR)) {
-				for (int j = 0; j < agentStrategies.length; j++) {
-					agentBeliefs[i][j] = 0.0;
-					gameValue[i][j] = 0.0;
+		

Is this tabbed too much?
Where do you use him in the setBeliefs function?

In src/agents/Agent.java:
> +	}
+	
+	/**
+	 * superRationalWithDiscountFactor method defines algorithm for identifying opponent's expected cooperating ratio
+	 * in order to make a decision that maximize its expected return.
+	 * 							 
+	 * @param opponentCooperateRatio	:	Expected ratio at which opponent cooperates	
+	 * @param requestingAgentID			:	agent experiment ID
+	 * @param agentStrategy				:	opponent Strategy
+	 * @param opponentID				: 	opponent experiment ID
+	 * @return							:	agent's action
+	 */
+	private char superRationalWithDiscountFactor(double opponentCooperateRatio, int requestingAgentID,String agentStrategy, int opponentID) {
+		char matchAction; // Set default action
+
+		if(opponentFirstAct != "D"){

Do you have a constant for "D"?

In src/agents/Agent.java:
>  		}
+		
+		else{
+		
+			// Find opponent defect ratio
+			double opponentDefectRatio = 1.0 - opponentCooperateRatio;
+		
+		

Add error handling for divide by zero errors

In src/agents/Agent.java:
>  	}
 
 	
+	/**
+	 * dummy strategy returns a non-computable strategy 'A'
+	 * 
+	 * @return DUMMY : 'D'
+	 * 
+	
+	 */
+	char dummy() {

Do you need this? Where do you use it?

In src/agents/Agent.java:
>  	
 	/**
-	 * requestRandomTournament method provides the mechanism for advanced agents
-	 * to randomly choose a tournament and request opponent's past information.
+	 * getOpponentPastInfo request for past opponent action from the HIM and

Update parameters

In src/agents/Agent.java:
> +				matchAction = superRationalWithDiscountFactor(opponentCooperateRatio, requestingAgentID,agentStrategy, opponentID);
+		}
+		return matchAction;
+	}
+	
+	
+	/**
+	 * DefectAll strategy defects at all times no matter what the opponent does
+	 * 
+	 * @return DEFECT : 'D'
+	 * 
+	 *         The algorithm and code structure for the DefectAll Strategy was
+	 *         taken and modified from
+	 *         http://www.prisoners-dilemma.com/java/ipdlx/ipdlx_javadocs/
+	 * 
+	 */
 	char defectAll() {

Again do you use this anywhere?

In src/agents/Agent.java:
> +		if (((currentTournament == 0) && (currentRound == 0))) {
+			matchAction = COOPERATE;
+		}
+
+		// Act based on updated beliefs from past information
+		else {
+			double opponentCooperateRatio = getOpponentPastInfo(requestingAgentID,
+					opponentID, infoRequestOption,agentStrategy);
+			
+			
+			//Update agent's belief about opponent cooperating ratio
+			setOpponentCooperateRatio(requestingAgentID,opponentID,opponentCooperateRatio);
+
+			
+			// Get opponent's updated cooperating ratio
+			double opponentCooperatingRating = 	getOpponentCooperateRatio(requestingAgentID,opponentID,opponentCooperateRatio);

Formatting issue

In src/agents/Agent.java:
> +
+		// Act based on updated beliefs from past information
+		else {
+			double opponentCooperateRatio = getOpponentPastInfo(requestingAgentID,
+					opponentID, infoRequestOption,agentStrategy);
+			
+			
+			//Update agent's belief about opponent cooperating ratio
+			setOpponentCooperateRatio(requestingAgentID,opponentID,opponentCooperateRatio);
+
+			
+			// Get opponent's updated cooperating ratio
+			double opponentCooperatingRating = 	getOpponentCooperateRatio(requestingAgentID,opponentID,opponentCooperateRatio);
+			
+			// Promote cooperation with Naive Cooperators
+			if ((opponentCooperatingRating >= 0.9)||(opponentFirstAct == "C")){

Formatting issue

In src/agents/Agent.java:
> +	private double getOpponentPastInfo(int requestingAgentID,
+			int opponentID, int infoRequestOption, String agentStrategy) {
+
+		String opponentInformation = "";
+		
+		double opponentCooperateRatio = 0;
+
+		switch (infoRequestOption) {
+
+		// Get opponent's first action
+		case 0:
+			opponentInformation = him.requestOppPastInfo(requestingAgentID,
+					opponentID, infoRequestOption);
+			
+			if (infoAcquired) {
+				if (opponentInformation.equalsIgnoreCase("D"))

Do you have a constant for "D"?

In src/agents/Agent.java:
>  
-		// Generate Random tournament
-		Random rand = new Random();
-		int randomTournamentNumber = rand.nextInt((currentTournament - 0) + 1);
+		// Request all opponent's past actions
+		case 2:
+			opponentInformation = him.requestOppPastInfo(requestingAgentID,
+					opponentID, infoRequestOption);
+			if ((infoAcquired)){
+				if((!opponentInformation.isEmpty())){

Could you do an "&&" here for infoAcquired and opponentInformation conditions

In src/agents/Agent.java:
> -		int randomTournamentNumber = rand.nextInt((currentTournament - 0) + 1);
+		// Request all opponent's past actions
+		case 2:
+			opponentInformation = him.requestOppPastInfo(requestingAgentID,
+					opponentID, infoRequestOption);
+			if ((infoAcquired)){
+				if((!opponentInformation.isEmpty())){
+					opponent [...]

2018-05-07 05:48 UTC, merged